[IV-23-24] Objetivo 0
LuciaAnsino/CompraOnline pull request #1
Opened 2023-09-19 07:41 UTC by LuciaAnsino

- [ ] ¿Se trata de un problema real del que se tenga conocimiento personal?

- [ ] ¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?

- [ ] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando?

- [ ] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el README?

- [ ] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas a requerir que el usuario los introduzca?

- [ ] ¿Has seguido la lista de comprobación o estás marcando al buen tuntún todo?

2023-09-19 09:20 UTC, JJ commented
Deberías configurar el avatar de la cuenta para que no fuera el que hay por defecto. Es uno de los prerrequisitos de este objetivo.

2023-09-19 09:22 UTC, JJ requested changes
Aunque de la contestación a las preguntas he comprendido que lo que quieres hacer es extraer información de tickets de compra electrónicos, eso no lo has puesto en la descripción del problema y por lo tanto no "está" en la descripción del mismo. Por favor, explica correctamente el problema que quieres solucionar *en el README*

2023-09-20 06:11 UTC, JJ requested changes
Entender y expresar el problema claramente es clave para poder emprender el proyecto. Como pone en los [errores comunes](https://github.com/JJ/IV-/blob/master/sesiones/errores-objetivo-0.md):

> Expresar el problema como "la persona *quiere* o *desea*". Esto será, en todo
  caso, una expresión de una posible solución a un problema (que puede tener
  otras muchas y que, en todo caso, es algo que hay que explorar durante el
  desarrollo). Un problema será, en todo caso, lo que causa que esa persona
  quiera hacer esa actividad (o cualquier otra que pueda resolverle el
  problema).

Cuando esté listo, simplemente márcalo como "listo para revisar" o hazme una referencia con mi nick en un comentario.
Por otro lado, permíteme recordarte que lo más eficiente es que cuando recibas la corrección, intentes corregirla a la mayor celeridad, para no retrasar el comienzo del objetivo siguiente, y simplemente para poder tener todavía presente el contexto del envío original. Yo trato de evaluar con la mayor rapidez posible por la misma razón.

2023-09-20 06:11 UTC, JJ commented on README.md
> +Soy una persona que realiza compras que le gustaría saber al realizar una compra los productos comprados anteriormente, para evitar comprar cosas que ya obtuve con anterioridad y ver posibles errores
¿"Saber los productos comprados anteriormente" es el problema? ¿No será el problema la razón por la que quiere saber esos productos?

2023-09-20 08:49 UTC, LuciaAnsino commented
Ya lo he modificado.

2023-09-20 08:58 UTC, JJ requested changes
Una vez más, tal como lo planteas ("no recuerda las tallas") no parece que vaya más allá de almacenar (las tallas) y recuperarlas.

Lo que te aconsejaría en este caso es que repitieras el juego mañana. Llévate las fichas que rellenaste, y lo vemos conmigo u otro compañero. Alternativamente, simplemente trata de llevar tú a cabo la fase de empatización del diseño de un producto, identificando claramente el tipo de cliente, el problema y cómo se podría resolver ese problema con una lógica de negocio no trivial (que vaya implícita en la formulación del problema)

2023-09-20 08:58 UTC, JJ commented on README.md
> +Para ello, el comprador debe de subir su ticket de compra que será analizado. De ahí se extraerá la información necesaria para que él sepa los productos que ha comprado con anterioridad e información
Sigues proponiendo una solución sin exponer el problema.

2023-09-20 08:58 UTC, JJ commented on README.md
> +Soy una persona que realiza compras que quiere evitar comprar productos innecesarios saber errores cometidos durante las compras, por ejemplo, productos que hayan sido comprados anteriormente o compr
Por favor, cuida los errores de typeo.
Por otro lado, una vez más, el problema no está expuesto claramente ni está claro cuál es el problema.

La metodología de *design thinking* precisamente ayuda en eso, en su primera fase, que es la empatización, y para la empatización lo primero que hay que hacer es identificar cuál es el cliente. Por lo que describes aquí, parece un cliente al que se le olvidan cosas o "no recuerda tallas". Tallas ¿de qué? ¿Qué tipo de compra está haciendo? ¿Las tallas de algo aparecen en el ticket?

2023-09-20 11:29 UTC, LuciaAnsino commented
He planteado otro problema.

2023-09-20 12:12 UTC, JJ requested changes
Gracias por volver a intentarlo. Dado que tienes conocimiento personal del tema y cierto interés en el asunto, ¿podría ser que hubiera algún problema de extracción de información poco estructurada que pudiera usarse aquí? Por ejemplo, cada cooperativa muestra los precios a los que compra el aceite en una página web, y hay que extraer de ahí esos precios procesando el texto o el HTML.
También podría ser que hubiera diferentes cooperativas que compraran el aceite (ya sé que es complicado si no eres socio, pero a ver) y te pueda convenir extraer ese precio puntual y ver si la diferencia en el precio del carburante es suficiente como para ir a una que está más lejos en vez de otra más cercana.
Por otro lado, un algoritmo simple de predicción de precios, si es que no se publican los precios al día, podría ser conveniente, una vez que se extraigan de una fuente estructurada o no.
Piensa en estas cosas (o habla con esos familiares para que te cuenten algún problema que se pueda solucionar extrayendo datos de algún lugar, procesándolos, y dando una solución que sirva en un momento determinado). Ánimo.

2023-09-20 12:12 UTC, JJ commented on README.md
> +Soy el dueño o empleado de una cooperativa de aceite y necesito saber en que sala de la cooperativa se encuentran el resto de compañeros, para poder localizarlos con mayor facilidad. También, es cruc
Vamos a ir por partes:

> Soy el dueño o empleado de una cooperativa de aceite

Las cooperativas no tienen dueños (si acaso, encargados), pero las necesidades de un dueño van a ser muy diferentes de las de los empleados.

> y necesito saber en que sala de la cooperativa se encuentran el resto de compañeros

De [los errores frecuentes](https://github.com/JJ/IV-/blob/master/sesiones/errores-objetivo-0.md);

> Expresar el problema como "la persona quiere o desea". Esto será, en todo caso, una expresión de una posible solución a un problema (que puede tener otras muchas y que, en todo caso, es algo que hay que explorar durante el desarrollo). Un problema será, en todo caso, lo que causa que esa persona quiera hacer esa actividad (o cualquier otra que pueda resolverle el problema).

El problema a resolver sería, en todo caso, la razón por la que necesita saber dónde están el resto de los compañeros. ¿En todas las salas tiene que haber un mínimo de personas? ¿Hay suficientes personas para todas las salas?

> , para poder localizarlos con mayor facilidad.

Esto sería una posible solución, pero no está claro a qué problema. En todo caso, en el guión hemos puesto que cualquier problema que requiera input excesivo por los usuarios (decir en todo momento donde está) o conexiones físicas (¿un detector de NFC de los móviles?) no serían adecuados para esta asignatura

> También, es crucial llevar un registro de donde ha estado cada empleado a que horas a lo largo del día 

Para resolver, ¿qué problema? 

> y evitar que algunas salas se queden desatendidas por los empleados, por ejemplo, la sala donde se atiende a los clientes.

Si el problema es asignar empleados a diferentes lugares, tendrás que especificar claramente cuál es el contexto, si es un problema de scheduling, por ejemplo, o un problema de asignación de tareas. En cualquiera de los dos casos, sería imprescindible tener conocimiento personal del tema porque saber cuándo se reparten tareas, qué tipo de restricciones tienen, y demás, es imprescincible para poder resolverlo.

2023-09-20 12:12 UTC, JJ commented on README.md
> +Por lo que, se dirá donde se encuentra un empleado en el instante de la consulta y también la gente qu hay en ese instante en una sala concreta. Además, se deberá poder consultar un historial que ind
En el [guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio) habla de los problemas que no serían adecuados para esta asignatura, los que incluyan palabras como

> “buscar”, “dar de alta”, “poner en contacto”, “recuperar”, “integrar”, “alertar”, “comunicar”.

... o "consultar" o "decir". "Historial" es simplemente una lista, es otra palabra para "recuperar".

Si se trata de un problema de scheduling, puede ser simple o muy complicado de solucionar; pero no veo cómo podría esto tener una lógica de negocio compleja más allá de "enviar a las salas vacías una persona que esté en una sala donde haya más gente". Y una solución compleja, que sería la real, creo que se escapa a esta asignatura, me temo.

2023-09-20 13:29 UTC, LuciaAnsino commented
Ya lo he modificado.

2023-09-20 15:37 UTC, JJ requested changes
Parece que te estás acercando a una descripción de un problema; te aconsejaría que siguieras por ahí para llegar a una descripción que te permita superar este objetivo.

2023-09-20 15:37 UTC, JJ commented on README.md
> +Soy el dueño de una envasadora de aceite y necesito saber a que precio debo de vender el aceite ya envasado para obtener beneficio, debido a que cada vez que se neceditan mas suministros por ejemplo
Dejemos de lado que una vez más, existe el problema de que hablas de lo que el cliente "necesita", en vez de qué problema hay. Enunciar un problema no es decir lo que se quiere o se necesita hacer (que eso se decidirá en el proceso del desarrollo), sino qué es lo que ocurre que provoca insatisfacción. ¿Es imposible saber el precio de venta cuando uno quiere vender? ¿O cuando debe uno vender, sabiendo que el precio es el más adecuado? ¿Se busca maximizar las ventas? ¿El beneficio?

Adicionalmente, el problema enunciado debe tener una serie de características para que sea válido: que se tengan los datos para tomar la decisión, por ejemplo. No está claro ni siquiera qué datos son los necesarios para tomar la decisión, ni qué procesamiento habrá que hacer sobre esos datos y si será complejo o no.

2023-09-20 17:55 UTC, LuciaAnsino commented
Ya lo he modificado centrandome más en el problema.

2023-09-21 05:33 UTC, JJ requested changes
En el proceso de *design thinking* lo que se busca es precisamente identificar el problema. Quizás lo mejor sea repetir el proceso para, en este contexto, poder describir correctamente el problema para poder empezar a trabajar con él.

2023-09-21 05:33 UTC, JJ commented on README.md
> +Soy el dueño de una envasadora de aceite que desperdicia muhco tiempo recopilando las facturas de cada elemento necesario para envasar el aceite (como las botellas, tapones, cajetas, aceite, portes..
¿El problema consiste en recopilar las facturas o procesar las facturas o calcular el precio? ¿El cálculo del precio es una operación aritmética simple o se trata de aplicar algún tipo de algoritmo?
Cuida también los errores de tipeo, por favor.

2023-09-21 07:28 UTC, LuciaAnsino commented
Ya he actualizado la información.

2023-09-21 11:39 UTC, JJ requested changes
Último [error frecuente actualizado hoy](https://github.com/JJ/IV-/blob/master/sesiones/errores-objetivo-0.md)

> Escribir el problema sobreentendiendo lo que se ha hablado en clase con el profesor. Se debe entregar de forma que incluso un profesor olvidadizo, u otro, entienda de qué se está hablando.

Recuerda que esto es el problema que te permite iniciar un proyecto de desarrollo. No "lo que pide el profe". El profe no tiene por qué entrar en la ecuación, ni saber nada aparte de lo escrito.

2023-09-21 11:39 UTC, JJ commented on README.md
> +Soy una persona que no tengo disponible todas las compras que realizo y siempre que voy a comprar acabo comprando productos que ya tenía.
De veras, Lucía, pégale una vuelta más al tema. Sigue sin estar claro cuál es el problema, ni dónde compras, ni qué productos son, ni nada de nada.

2023-09-21 12:01 UTC, LuciaAnsino commented
@JJ creo que ahora está más claro.

2023-09-21 12:02 UTC, JJ approved these changes
:+1:

2023-09-22 07:09 UTC, merged

2024-03-03 17:14 UTC, Gdakgdak22 approved these changes