Objetivo 1
LuciaAnsino/CompraOnline pull request #2
Opened 2023-09-24 17:55 UTC by LuciaAnsino

2023-09-24 20:20 UTC, Morad02 commented
Hola, me ha tocado ser su revisor. 
Los milestones me parece que están bien y se ajustan a lo que se pide. En cuánto a las historias de usuario, las dos tienen la misma lógica de negocio por lo que con una bastaría. El contexto que se utiliza para describirla creo que es suficiente, pero te recuerdo que las historias de usuario expresan los deseos de los usuarios sin que haga falta hacer alusiones  a cómo se resolvería el problema.

2023-09-25 17:42 UTC, LuciaAnsino commented
@Morad02 ya lo he modificado

2023-09-25 18:25 UTC, LuciaAnsino commented
@Morad02 he creado un nuevo fichero con información de user journey y modificado el HU2

2023-09-25 18:36 UTC, Morad02 approved these changes
Creo que al añadir el user journey todo queda más claro.  Avisa al profesor para la revisión. Suerte!

2023-09-25 19:14 UTC, LuciaAnsino commented
@JJ Listo para revisión

2023-09-26 06:45 UTC, JJ requested changes
Conviene que entendáis realmente qué implica el primer milestone (milestone 0), que es entender el problema, haciendo un modelo del mismo, no "diseñarlo"

2023-09-26 06:45 UTC, JJ commented on docs/milestone.md
> +## [M0] Diseño del problema
El problema no necesita diseño, sino un modelo.

2023-09-26 07:39 UTC, LuciaAnsino commented
@JJ Ya he entendido al concepto.

2023-09-26 07:41 UTC, JJ approved these changes
:+1:

2023-09-29 06:42 UTC, merged