[IV-23-24] Objetivo 5
LuciaAnsino/CompraOnline pull request #26
Opened 2023-12-01 09:02 UTC by LuciaAnsino

* [ ] ¿Se han establecido criterios previos de elección de la imagen base, así
como los criterios de búsqueda que han conducido a las imágenes que se están considerando?
* [ ] ¿Se ha tenido en cuenta que la imagen es para testear, y que por tanto
tiene una función específica, tal como testear cómo va nuestra aplicación en la última versión publicada del lenguage?
* [ ] ¿Se ha tenido en cuenta que la versión de la imagen base sea la última?
* [ ] ¿Se han tenido en cuenta criterios reales para la elección, y no criterios
irrelevantes como cuanto tiempo se tarda en construirla? (Se va a construir una vez, se va a usar cientos o miles de veces)
* [ ] ¿Se han seguido las buenas prácticas en las órdenes que construyen  la imagen? ¿Especialmente las relativas a usuarios no privilegiados y demás?
* [ ] ¿La imagen incluye sólo y exclusivamente la infraestructura
   necesaria para pasar los tests? Por ejemplo, si se ha elegido la imagen
   "oficial" (lo que hay que hacer sólo en casos muy justificados) ¿se ha
   comprobado que lo que se instale sea sólo y exclusivamente lo necesario para nuestro proyecto?
* [ ] ¿Se han documentado y enlazado los commits a las imágenes que se han testeado?
* [ ] ¿Está establecido correctamente como `WORKDIR` el que se va a usar en los tests que se van a lanzar?
* [ ] ¿Se usa algún directorio adecuado para copiar contenidos del repositorio
en vez del directorio de trabajo?
* [ ] ¿Se han establecido claramente los criterios de búsqueda y de aceptación de
   la imagen base?
* [ ] ¿Tienes claro cuales son las condiciones en las que tiene que actualizarse
la imagen en DockerHub y has configurado el workflow de acuerdo con ello? En particular, ¿sabes qué condiciones tienen que darse para que se actualice y qué condiciones *no* deben darse?
* [ ] Si se usan GitHub actions para su publicación, ¿se han considerado
cuidadosamene los criterios (ramas, paths) para que se lancen?
* [ ] ¿Se ha comprobado que el ENTRYPOINT del contenedor no escriba nada en el directorio que monta, ya que no tiene derecho de escritura?
* [ ] ¿Se ha abierto un shell en el contenedor una vez construida la imagen y
comprobado que los ficheros que se necesitan están todos incluidos, y que no hay ficheros que no se necesiten?

2023-12-04 15:17 UTC, pluque01 reviewed
Hola! Te dejo algunos comentarios que espero sean de utilidad. :))

2023-12-04 17:03 UTC, LuciaAnsino commented on Dockerfile
> +ENV NODE_VERSION 21.3.0
El label lo que indica es quien se encarga de esa imagen y en caso de la variable de entorno sirve para indicar la versión de node que se desea usar

2023-12-04 17:15 UTC, LuciaAnsino commented on docs/eleccion_imagen.md
> +Considero que lo mejor es usar la imagen base de Node.js, ya que viene preparada para usar node. No obstante, para reducir el tamaño considero que lo mejor sería usarla con alguna de sus etiquetas y
Resuelto en [9308d6e](https://github.com/LuciaAnsino/CompraOnline/pull/26/commits/9308d6e0b20d6dd3098eae02eb23d9a0e814f458)

2023-12-04 17:15 UTC, LuciaAnsino commented on Dockerfile
> +#RUN chown -R node:node /usr/local/lib/node_modules/
Resuelto en [2a762eb](https://github.com/LuciaAnsino/CompraOnline/pull/26/commits/2a762eb2e432dc9442d6b8c8396d837c7313e0d5)

2023-12-04 17:19 UTC, LuciaAnsino commented on .github/workflows/contenedor.yml
> +      uses: docker/login-action@v3
Resuelto [609278b](https://github.com/LuciaAnsino/CompraOnline/pull/26/commits/609278b7c573c9d204eb1a43d88f23eee3b79431)

2023-12-04 17:20 UTC, migueruiz approved these changes
Muy buen trabajo! suerte en la revisión 😄

2023-12-05 10:47 UTC, pluque01 commented on Dockerfile
> +RUN mkdir /.pnpm && chmod 777 /.pnpm
Seguramente haya una combinación de permisos mínimos con los que funciona, pero si prefieres déjalo así

2023-12-05 10:56 UTC, pluque01 commented on Dockerfile
> +ENV NODE_VERSION 21.3.0
¿Y el uso de la variable de entorno te funcionaría si por ejemplo pusieses NODE_VERSION a otra que no fuese 21.3.0? 

Que yo sepa la versión de node viene dada por la imagen de docker, en tu caso estas usando `node:bookworm-slim` donde la versión de node es la 21.3.0.

Con esto quiero decir que debería ser en la imagen donde definas qué versión de node vas a usar, como por ejemplo `FROM node:21.3.0-bookworm-slim`

2023-12-09 19:24 UTC, LuciaAnsino commented
@pluque01 listo para revisión

2023-12-10 12:18 UTC, pluque01 approved these changes
No sé si viste los comentarios que te dejé en la anterior conversación. Échale un vistazo si puedes pero yo te doy mi okey.

2023-12-12 11:51 UTC, LuciaAnsino commented
@pluque01 no se por qué pero además de los comentarios que resolví no me salen más comentarios. De igual forma gracias.

2023-12-12 12:27 UTC, pluque01 commented
> @pluque01 no se por qué pero además de los comentarios que resolví no me salen más comentarios. De igual forma gracias.

Te comenté en los comentarios resueltos 😅

2023-12-13 17:35 UTC, LuciaAnsino commented on Dockerfile
> +ENV NODE_VERSION 21.3.0
Si funcionaria, es decir si modifico la versión en la variable de entorno la versión que se usaría cambiaría a lo modificada. Esto es así debido a que cuando se construye la imagen se usa esa variable de entorno para usar la versión de Node.js especificada. No obstante se puede hacer poniendo FROM node:21.3.0-bookworm-slim, son diferentes formas de indicar la versión.

2023-12-13 17:35 UTC, LuciaAnsino commented
@JJ Listo para revisión

2023-12-13 18:13 UTC, JJ requested changes
Muchas gracias a @migueruiz y a @pluque01 por la ayuda; creo que iban en la buena dirección.

2023-12-13 18:13 UTC, JJ commented on Dockerfile
> +ENV NODE_VERSION 21.3.0
> El label lo que indica es quien se encarga de esa imagen y en caso de la variable de entorno sirve para indicar la versión de node que se desea usar

La versión de node es la que tiene la imagen base. Por favor, hazle caso a @pluque01 que creo que va por buen camino.

2023-12-13 18:13 UTC, JJ commented on Dockerfile
> +RUN npm install -g pnpm@latest
¿Seguro que no puedes instalar pnpm sin necesitar npm? ¿No te das cuenta que si tienes las dos cosas en la imagen estás incluyendo más cosas de las necesarias?

2023-12-13 18:13 UTC, JJ commented on docs/eleccion_herramientas_test.md
> ++ [Vitest](https://vitest.dev/): Tiene mayor puntuación que todos (98) es el que mejor rendimiento tiene y al ser parte del ecosistema Vite se beneficia de la extensa documentación de este. Además, p
OK, entiendo que esto es por no usar vitest al final, pero habría preferido que hicieras el cambio antes del PR.

2023-12-13 18:13 UTC, JJ commented on docs/eleccion_imagen.md
> +## Opciones
Hay más opciones que las que comentas. Además, en clase os expliqué que era conveniente que intentárais usar imágenes sólo con el sistema operativo e instalar node por vuestra cuenta. Si no quieres hacerlo es decisión tuya, pero sí tendrás que hacer un pequeño esfuerzo en considerar otras imágenes que no sean estrictamente las oficiales.

2023-12-13 18:13 UTC, JJ commented on docs/eleccion_imagen.md
> ++ [Fedora](https://hub.docker.com/_/fedora), es una imagen que no contiene por defecto Node.js no obstante se podría instalar. Su tamaño es de 64.9 MB y la última vez que fue actualizada fue hace 5 d
Estás comparando en todo caso imágenes con node con imágenes con sólo el sistema operativo. Por fuerza van a ser diferentes.

2023-12-15 08:48 UTC, LuciaAnsino commented
@JJ listo para revisión

2023-12-15 09:16 UTC, JJ requested changes
Resuelve los comentarios, porfa.

2023-12-15 09:16 UTC, JJ commented on docs/eleccion_imagen.md
> +## Opciones
Porfa, resuelve los comentarios que queden por aquí.

2023-12-15 09:16 UTC, LuciaAnsino commented on docs/eleccion_imagen.md
> ++ [Fedora](https://hub.docker.com/_/fedora), es una imagen que no contiene por defecto Node.js no obstante se podría instalar. Su tamaño es de 64.9 MB y la última vez que fue actualizada fue hace 5 d
Resuelto en [5d87ffb](https://github.com/LuciaAnsino/CompraOnline/pull/26/commits/5d87ffbd12a6b095c734e43a8b1459d734f88e87)

2023-12-15 09:17 UTC, LuciaAnsino commented on docs/eleccion_imagen.md
> +## Opciones
Resuelto en [5d87ffb](https://github.com/LuciaAnsino/CompraOnline/pull/26/commits/5d87ffbd12a6b095c734e43a8b1459d734f88e87)

2023-12-15 09:17 UTC, LuciaAnsino commented on Dockerfile
> +RUN npm install -g pnpm@latest
Resuelto en [d562bcf](https://github.com/LuciaAnsino/CompraOnline/pull/26/commits/d562bcf9fe853e445df0114daafcf77c58696af7)

2023-12-15 09:18 UTC, LuciaAnsino commented
@JJ Listo

2023-12-15 09:22 UTC, JJ approved these changes
👍

2023-12-21 07:57 UTC, merged