[IV-23-24] Objetivo 6
LuciaAnsino/CompraOnline pull request #33
Opened 2023-12-21 10:38 UTC by LuciaAnsino

- [ ] ¿Se han establecido criterios a priori para elegir el sistema de
integración continua más conveniente y se han calificado los sistemas que
cumplan esos requisitos según esos criterios?

- [ ] ¿Se han examinado varios sistemas de integración continua?

- [ ] ¿Se han configurado varios sistemas de integración continua?

- [ ] ¿Se ha configurado correctamente el Checks API en los sistemas en los que
sea necesario para que aparezca correctamente en GitHub (y se pueda comprobar desde los tests)?

- [ ] ¿Uno de los sistemas configurados permite comprobar cuales son las versiones dellenguaje con las que funciona correctamente nuestra aplicación?

- [ ] ¿Se escogen de forma adecuada las versiones del lenguaje que se testean,
 tanto en el sistema de CI como en el contenedor Docker?

- [ ] ¿Se han justificado correctamente las versiones del lenguaje que se están
testeando y se ha comprobado que no se comprueban varias veces lo mismo (la
misma versión en CI y en el contenedor Docker en otro sistema CI?

2023-12-23 18:28 UTC, migueruiz approved these changes

2023-12-25 13:40 UTC, MarioGuisado commented on appveyor.yml
Deberías quitar los comentarios.

2023-12-25 13:41 UTC, MarioGuisado approved these changes

2023-12-28 18:33 UTC, LuciaAnsino commented on appveyor.yml
Resuelvo en [e6f2817](https://github.com/LuciaAnsino/CompraOnline/pull/33/commits/e6f2817bd300877afe9ff29a7f661cfa9567df2b)

2023-12-28 18:33 UTC, LuciaAnsino commented
Listo para revisión @JJ

2023-12-28 18:42 UTC, JJ requested changes
Me temo que no estás testeando usando el contenedor en ninguno de los sistemas de CI configurados.
Creo, además, que estás testeando la versión 20 de node dos veces. Por favor, compruébalo.

2024-01-06 12:48 UTC, LuciaAnsino commented
@JJ ya he usado docker y solo testeo la verisón 20 una unica vez en AppVeyor, la versión dev es la que se usa por defecto en el docker y con Github Actions testeo la lts.

2024-01-06 12:53 UTC, JJ approved these changes
:+1:

2024-01-13 11:55 UTC, merged