Objetivo 2 [IV-23-24]
LuciaAnsino/CompraOnline pull request #6
Opened 2023-10-19 07:43 UTC by carlotiii30

Sobre la estructura del repositorio

* [ ] ¿He seguido las mejores prácticas en el nombre de las clases y ficheros y
   disposición de los mismos?
* [ ] ¿He mirado tanto reglas generales (para cualquier repo) como reglas
específicas para el lenguaje con el que se está trabajando?

Sobre el planteamiento

* [ ] ¿Se han planteado una serie de issues, asignados a las historias de
usuario pertinentes, que clarifiquen qué es lo que necesitan los usuarios e
identifiquen las diferentes partes del problema?
* [ ] ¿Los issues representan un problema, y no una tarea?

Sobre el análisis del problema

* [ ] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo
   que se ha creado?
* [ ] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor,
   una entidad o un agregado?
* [ ] ¿He propuesto un producto mínimamente viable, que en muchos casos será un solo
   objeto valor que no dependa de ningún otro (y que sea la base de muchos
   otros)?.

Sobre el código

* [ ] ¿Todos los mensajes de commit explican el cambio, y no se
      limitan a repetir el nombre del fichero que se ha cambiado?
* [ ] ¿Los mensajes de commit siguen el formato estándar y buenas prácticas?
* [ ] ¿Se ha hecho una revisión real del código para comprobar que todos
   los atributos y funciones creadas están respaldadas por una HU?
* [ ] ¿Todos los issues creados están relacionados con a una HU?
* [ ] ¿Ha asignado el propietario/la propietaria del repositorio todos los
issues planteados al *milestone* correspondiente?
* [ ] ¿Todos los cambios en el código están asignados a un issue al que se
      referencia en un commit?
* [ ] ¿Se ha asignado al mismo milestone el PR que se ha hecho?
* [ ] ¿Es el milestone sobre el que estoy trabajando un producto
   mínimamente viable? ¿O tengo que solicitar al product manager que precise de
   qué producto se trata?
* [ ] ¿Se ha comprobado que el código entregado sea sintácticamente
correcto?

2023-10-20 09:56 UTC, LuciaAnsino commented on src/Alimento.ts
> +    private fecha_caducidad: Date;
Para resolver las HU no necesito saber ni la caducidad ni el precio de venta y compra del alimento, es información irrelevante.

2023-10-20 09:56 UTC, LuciaAnsino commented on src/Alimento.ts
> +class Alimento {
¿Es el alimento el objeto valor?, en ese caso con el propio alimento se puede identificar, sin necesidad de tener un codigo asociado a él, en este caso con el propio nombre valdría

2023-10-20 09:56 UTC, LuciaAnsino commented on iv.yaml
> +entidad: src/Alimento.ts
Alimento no sería la entidad, ya que hay otros elementos que engloban muchos más elementos, inclusive alimento

2023-10-20 09:56 UTC, LuciaAnsino commented on src/TicketElectronico.ts
> +    private precio_alimento: number; // Cantidad x precio unidad
El precio de la compra y del alimento no es necesario para resolver el problema. Además, en un ticket se proporciona la cantidad de cada alimento que se compra y ahí no se refleja dicha información.

2023-10-20 09:56 UTC, LuciaAnsino commented on src/Alimento.ts
> +    private nombre: string;
El nombre del producto una vez creado no se debería de poder modificar por lo que creo que sería mejor que fuera readonly

2023-10-22 11:07 UTC, carlotiii30 commented on src/Alimento.ts
> +    private fecha_caducidad: Date;
Para la segunda historia de usuario, para las ganancias, ¿no necesitarías saber el beneficio de cada alimento?

2023-10-23 09:41 UTC, LuciaAnsino commented on src/Alimento.ts
> +    private fecha_caducidad: Date;
Creo que no has entendido bien lo que se requiere en la segunda HU. En ella se dice que le interesa saber cuales son los productos más vendidos para que la empresa con dicha información coloque los productos sabiendo esa información de forma que se incite al cliente a comprar más. En ningún momento se necesita saber el coste de los productos.

2023-10-26 11:53 UTC, LuciaAnsino reviewed
Te he recomendado unos cambios. 🏗️

2023-10-26 11:53 UTC, LuciaAnsino commented on src/Compra.ts
> +    private cantidad: number;
Has puesto cantidad como un único número, pero hay varios elementos. Entonces, no esta correctamente relacionado el alimento con la cantidad comprada de este.

2023-10-26 11:53 UTC, LuciaAnsino commented on src/Compra.ts
> +class Compra {
Puesto que los alimentos de una compra junto con sus cantidades una vez realizada no varían, te sugiero que los pongas readonly.

2023-10-27 06:52 UTC, LuciaAnsino commented
Creo que deberías actualizar los issues con los cambios que has ido realizando @carlotiii30.

2023-10-27 12:26 UTC, carlotiii30 commented
> Creo que deberías actualizar los issues con los cambios que has ido realizando @carlotiii30.

Muchas gracias, ya está hecho.

2023-10-30 10:42 UTC, LuciaAnsino commented
* [ ] ¿Los issues que ha planteado la persona son efectivamente problemas y evidencian comprensión de las historias de usuario? Si no es así, es mejor que se le transmita antes de que empiece a crear cualquier código erróneo.
* [ ] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de comprobación?
* [ ] ¿El código creado es una modelización válida de las historias de usuario creadas por ti, y te sirve como base para programar la lógica de negocio?
* [ ] ¿El código creado sigue las mejores prácticas para el lenguaje de programación que hayáis consensuado, tanto en identificadores, como nombres de ficheros, como disposición de los diferentes ficheros en el repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y aportan código para resolver el problema planteado en el mismo?
* [ ] ¿He comprobado que el código compile, o que quien lo ha programado ha lo ha hecho y documentado en el repositorio?
* [ ] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone correspondiente, que será el primero?
* [ ] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en el objetivo 4 para poder programar la lógica de negocio?
* [ ] En resumen, ¿considero que con lo hecho puedo ponerme a trabajar directamente en el siguiente milestone, que incluye la lógica de negocio?

2023-10-30 10:43 UTC, LuciaAnsino approved these changes
* [x] ¿Los issues que ha planteado la persona son efectivamente problemas y evidencian comprensión de las historias de usuario? Si no es así, es mejor que se le transmita antes de que empiece a crear cualquier código erróneo.
* [x] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de comprobación?
* [x] ¿El código creado es una modelización válida de las historias de usuario creadas por ti, y te sirve como base para programar la lógica de negocio?
* [x] ¿El código creado sigue las mejores prácticas para el lenguaje de programación que hayáis consensuado, tanto en identificadores, como nombres de ficheros, como disposición de los diferentes ficheros en el repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y aportan código para resolver el problema planteado en el mismo?
* [x] ¿He comprobado que el código compile, o que quien lo ha programado ha lo ha hecho y documentado en el repositorio?
* [x] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone correspondiente, que será el primero?
* [x] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en el objetivo 4 para poder programar la lógica de negocio?
* [x] En resumen, ¿considero que con lo hecho puedo ponerme a trabajar directamente en el siguiente milestone, que incluye la lógica de negocio?

2023-10-30 10:44 UTC, LuciaAnsino commented
Yo lo veo correcto, @JJ listo para revisión

2023-10-30 10:53 UTC, JJ requested changes
Por favor, tratad de seguir las mejores prácticas también en nombres de ficheros. En este caso específico, lo he repetido en clase varias veces y explicado la razón.

2023-10-30 10:53 UTC, JJ commented on iv.yaml
> +entidad: src/Compra.ts
No se usan mayúsculas en repositorios, porque en algunos sistemas de ficheros no las reconocen como tales.

2023-10-30 10:54 UTC, JJ commented
Commits como este [7747662](https://github.com/LuciaAnsino/CompraOnline/pull/6/commits/774766237edd2a0c0bb80c2b794444146b1d9830) no siguen las mejores prácticas. Incluso aunque se requieran cambios, siguen teniendo que ajustarse a un issue determinado y a una HU determinada, y en todo caso hay que explicarlos. Los commits sirven para documentar el código.

2023-10-30 10:56 UTC, JJ commented
Commits como este [3a287e8](https://github.com/LuciaAnsino/CompraOnline/pull/6/commits/3a287e8beeee2d8c0a81cccad220ffb7c3421383) tampoco siguen las mejores prácticas, porque es evidente lo que se ha añadido simplemente mirando al commit. Los mensajes de commit, una vez más, deben servir para documentar el código añadiendo información nueva y no repitiendo lo que ya se ve sólo mirando al commit (que se ha creado algo)

2023-11-02 08:48 UTC, carlotiii30 commented
@JJ Listo para revisión

2023-11-02 10:40 UTC, JJ commented
> * [x]  ¿Los issues que ha planteado la persona son efectivamente problemas y evidencian comprensión de las historias de usuario? Si no es así, es mejor que se le transmita antes de que empiece a crear cualquier código erróneo.

Permíteme que esté ligeramente en desacuerdo con esta afirmación, como he puesto en [este comentario](https://github.com/LuciaAnsino/CompraOnline/issues/10#issuecomment-1784949996)

> 
>     * [x]  ¿El código creado es una modelización válida de las historias de usuario creadas por ti, y te sirve como base para programar la lógica de negocio?

Si lo que he comentado arriba no sucede, esto puede ser también un problema. El ejercicio fundamental aquí tanto para @LuciaAnsino como para @carlotiii30 es hacer un recorrido por el modelo para programar la lógica de negocio y ver qué tenemos y qué no.

1. Se toma el ticket que estará en formato texto para procesarlo. ¿Lo tenemos?
2. Del ticket tenemos que extraer diferentes piezas de información. ¿Sabesmos qué piezas de información son y cómo encontrarlas en el ticket o cómo procesarlas?
3. Una vez tenemos esas piezas, ¿Qué es lo que hay que extraer y dónde hay que ponerlo?

En general, os aconsejaría que cerrárais los issues y abriérais otros nuevos, para no correr el riesgo de "reciclar" o el issue o el código que se ha llevado a cabo, que es incorrecto puesto que no ha seguido la metodología correcta para resolverlo. Para esto también lo mejor sería dejar sólo el `iv.yaml` en este PR, cerrar desde el cuerpo del PR todos los issues que no se vayan a llevar adelante, y abrir otro nuevo. No es necesario que se vuelva a enviar a `IV-`, pero sí es conveniente porque así se le pueden asignar algunos otros revisores que puedan echar una mano en el asunto.

2023-11-10 08:42 UTC, carlotiii30 commented
@LuciaAnsino He cambiado todas las clases y planteado los issues desde el principio. ¿Puedes revisarlo?

2023-11-10 09:40 UTC, LuciaAnsino approved these changes

2023-11-10 10:07 UTC, carlotiii30 commented
@JJ Listo para revisión

2023-11-10 10:15 UTC, JJ approved these changes
👍

2023-11-10 10:58 UTC, JJ commented
Convendría @carlotiii30 que comenzaras con el objetivo 3 lo antes posible.

2023-11-10 13:11 UTC, merged